global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: "auth"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["auth:8001"]

  - job_name: "ai-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["ai-service:8002"]

  - job_name: "db-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["db-service:8003"]

  - job_name: "cache-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cache-service:8004"]
